version: "3.9"
volumes:
  dbstore:
  
postgres:
  container_name: postgres_container
  image: postgres
  volumes:
    - dbstore:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=password

app:
  build: .
  environment:
    RAILS_ENV: development
  ports:
    - '3000:3000'
  volumes_from:
    - appdata
  links:
    - "postgres"

appdata:
  image: tianon/true
  volumes:
    - ".:/workspace"

pgadmin:
  container_name: pgadmin4_container
  image: dpage/pgadmin4
  restart: always
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: password
    PGADMIN_DEFAULT_PORT: 5432
  ports:
    - "5050:80"
